set(sources ${sources}
    src/ai/logic.cpp
    src/client/hiveClient.cpp
    src/client/tcp_Client.cpp
    src/hive/axialPosition.cpp
    src/hive/board.cpp
    src/hive/color.cpp
    src/hive/gameState.cpp
    src/hive/move.cpp
    src/hive/piece.cpp
    src/hive/pieceStack.cpp
    src/hive/pieceType.cpp
    src/hive/player.cpp
    src/hive/benchmark/benchmark.cpp
    src/hive/neighbourMap.cpp
    src/hive/globals.cpp
    src/communication/sc_Message.cpp
    src/communication/sc_MessageHandler.cpp
)